FROM node:20-alpine as build
WORKDIR /app
RUN apk add yarn

COPY . ./
RUN /bin/sh -c 'yarn install --check-files'
RUN yarn add react-scripts -g
RUN /bin/sh -c 'yarn build'

FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]
