version: '2'
services:
  backend:
    privileged: true
    container_name: backend
    environment:
      DRY_RUN: 'false'
    restart: always
    volumes:
      - ./backend/:/app
      - /app/node_modules/
    ports:
      - "8003:8003"
    build:
      context: backend/.
      dockerfile: Dockerfile
    # command: /bin/sh -c 'yarn run start'
    command: 'tail -f /dev/null'
    depends_on:
      - backend-db
  backend-db:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: appuser
      POSTGRES_DB: postgres